char *processaFile(FILE *fileIn);
bool endswith(char *file);
void help();
void risolviInclude(FILE *fileH);
char *getInclude(char *line);
void  processLine(char *line);
bool checkVar(char *name);
bool illegalChar(char *name);
extern int globalCommCount; 
extern int variableCount;
extern int nFileIclude;